### PR TITLE
Refactoring + Promises

### PR DESCRIPTION
**Pull request by rfdickerson**
Major changes in order to improve the organization and API by returning promises.
- Databases return promises
- `TodoItem` changed to `Task`
- Errors improved

### CODE REVIEW

**Comment by rfdickerson** [comment]
@jesspittman and @kunzmainali , can I get a code review?

**Comment by jesspittman** [comment]
This certainly looks cleaner without all of the oncompletion: @escaping stuff that was there before. Looks good.

**Comment by rfdickerson** [comment]
Cool, glad you like them 👍 

We can schedule sometime after all this Kitura 1.0 migration flurry has passed to figure out a game plan for introducing these changes.

**Comment by rfdickerson** [comment]
I'm closing this- since we aren't using TodoList-API anymore, anyhow. But, I think the things I did here are helpful.

**Pull request closed without merging**
